version: '3.8'

services:
  web:
    build: ./app
    ports:
      - [cite_start]"5000:5000"
    depends_on:
      - [cite_start]db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gestao_db
    networks:
      - [cite_start]rede_local

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      [cite_start]POSTGRES_DB: gestao_db
    volumes:
      - [cite_start]pg_data:/var/lib/postgresql/data
    networks:
      - rede_local

volumes:
  pg_data:

networks:
  rede_local: